query Movies($skip: Int!, $limit: Int!, $showing: ShowingMovie) {
  movies(skip: $skip, limit: $limit, showing: $showing) {
    status
    results {
      _id
      casts
      director
      end
      genres
      minutes
      poster
      producers
      production
      rate
      start
      synopsis
      theaters
      title
      writer
    }
    total
    access_time_in
    access_time_out
  }
}
